name: Deploy to Surge

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Surge
        run: npm install --global surge

      - name: Deploy to Surge
        run: surge ./ ledesma.surge.sh --token ${{ secrets.SURGE_TOKEN }}

